# Generated by Django 5.2.7 on 2025-10-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharehub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
