# Generated by Django 5.2.7 on 2025-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharehub', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college_dept',
            field=models.CharField(blank=True, choices=[('CCS', 'College of Computer Studies'), ('CNAHS', 'College of Nursing & Allied Health Sciences'), ('CEA', 'College of Engineering and Architecture'), ('CASE', 'College of Arts, Sciences and Education'), ('CMBA', 'College of Management, Business and Accountancy'), ('CCJ', 'College of Criminal Justice')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True),
        ),
    ]
