# Generated by Django 5.2.7 on 2025-11-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharehub', '0004_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='contact_information_visible',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='is_public',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='contact_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
