# Generated by Django 5.2.7 on 2025-11-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharehub', '0005_remove_usersettings_contact_information_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('condition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
