# Generated by Django 5.2.7 on 2025-11-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharehub', '0006_item_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
