# Generated by Django 5.2.7 on 2025-12-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharehub', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
