# Generated by Django 5.2.7 on 2025-12-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharehub', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
